### scalar 
- a number belongs to R
$$ 1 $$
### vector
- 1 dimensional array
$$\begin{bmatrix}
1 \\
4 \\
5
\end{bmatrix}$$

### Matrix
- 2 dimensional array
$$\begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6
\end{bmatrix}$$

### Tensor
- n dimensional array
$$\begin{bmatrix}
\begin{bmatrix} 1 & 2\\ 4 & 7 \end{bmatrix} & \begin{bmatrix} 1 & 2\\ 4 & 5 \end{bmatrix}\\
\begin{bmatrix} 5 & 1\\ 8 & 0 \end{bmatrix} & \begin{bmatrix} 2 & 0\\ 3 & 6 \end{bmatrix}\\
\end{bmatrix}$$

In [3]:
import torch
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.1+cpu


In [15]:
## introduction to tensors
# creating tensors

# scalar
scalar = torch.tensor(7)
print(scalar) # tensor(7)
print(scalar.ndim) # 0 (dimension) (number of nested arrays)

scalar2 = torch.tensor([[1, 2], [3, 4], [5, 6]])
print(scalar2) # tensor([[1, 2], [3, 4]])
print(scalar2.ndim) # 2 dimension (number of nested arrays)

scalar3 = torch.tensor([[1]])
print(scalar3) # tensor([[1, 2], [3, 4]])
print(scalar3.ndim) # 2 dimension (number of nested arrays)

tensor(7)
0
tensor([[1, 2],
        [3, 4],
        [5, 6]])
2
tensor([[1]])
2


In [16]:
print(scalar.item())
# print(scalar2.item()) # RuntimeError: a Tensor with 6 elements cannot be converted to Scalar
print(scalar3.item())


7
1


In [17]:
# vector
vector = torch.tensor([7, 7])
print(vector) # tensor([7, 7])
print(vector.ndim) # 1 dimension (vector essentially) (number of nested arrays)

vector2 = torch.tensor([[1, 2], [3, 4], [5, 6]])
print(vector2) # tensor([[1, 2], [3, 4]])
print(vector2.ndim) # 2 dimensional (matrix essentially) (number of nested arrays)

vector3 = torch.tensor([[[1]]])
print(vector3) # tensor([[1, 2], [3, 4]])
print(vector3.ndim) # 3 (tensor essentially) dimension (number of nested arrays)

tensor([7, 7])
1
tensor([[1, 2],
        [3, 4],
        [5, 6]])
2
tensor([[[1]]])
3


In [21]:
print(torch.tensor(5).size()) # empty []
print(vector.size()) # number of elements within each array in the tensor
print(vector2.size()) # number of elements within each array in the tensor
print(vector3.size()) # number of elements within each array in the tensor

torch.Size([])
torch.Size([2])
torch.Size([3, 2])
torch.Size([1, 1, 1])


In [22]:
# Matrix
matrix = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(matrix) # tensor([[1, 2, 3], [4, 5, 6]])
print(matrix.ndim) # 2 dimensional (matrix essentially) (number of nested arrays)

tensor([[1, 2, 3],
        [4, 5, 6]])
2


In [27]:
matrix.shape # size() and shape are the same

torch.Size([2, 3])

In [29]:
# Tensor

tensor = torch.tensor([[[3, 5], [7, 4], [1, 9]], [[0, 4], [2, 3], [7, 8]]])
print(tensor)
print(tensor.ndim) # 3 dimensional (matrix essentially) (number of nested arrays)
print(tensor.shape)

tensor([[[3, 5],
         [7, 4],
         [1, 9]],

        [[0, 4],
         [2, 3],
         [7, 8]]])
3
torch.Size([2, 3, 2])


### Convention
- scalar and vector variables are written in lowercase
- Matrix and tensor variables are written in uppercase

### Random Tensors
Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

1. start with random numbers
2. look at data
3. update those random numbers

In [30]:
# create a random tensor
random_tensor = torch.rand(3, 4)
print(random_tensor)
print(random_tensor.ndim) # 2 dimensional (matrix essentially) (number of nested arrays)
print(random_tensor.shape)

tensor([[0.4570, 0.2232, 0.8566, 0.6047],
        [0.4427, 0.5345, 0.3720, 0.1986],
        [0.5540, 0.5083, 0.3458, 0.0745]])
2
torch.Size([3, 4])


In [32]:
# create a random tensor 2
random_tensor = torch.rand(3, 2, 3, 2)
# random_tensor = torch.rand(size=(3, 2, 3, 2)) same as above
print(random_tensor)
print(random_tensor.ndim) # 4 dimensional (matrix essentially) (number of nested arrays)
print(random_tensor.shape)

tensor([[[[0.7433, 0.4354],
          [0.4217, 0.3716],
          [0.9967, 0.6850]],

         [[0.3957, 0.5961],
          [0.6487, 0.3949],
          [0.7772, 0.5608]]],


        [[[0.6163, 0.7421],
          [0.4071, 0.2285],
          [0.1541, 0.9107]],

         [[0.5673, 0.1467],
          [0.5392, 0.2337],
          [0.1985, 0.6632]]],


        [[[0.9868, 0.5535],
          [0.2247, 0.4455],
          [0.4509, 0.8464]],

         [[0.3166, 0.9207],
          [0.8202, 0.9271],
          [0.2324, 0.9213]]]])
4
torch.Size([3, 2, 3, 2])


In [41]:
# create a random tensor with similar shape to an image tensor
random_image_tensor = torch.rand(size=(224, 224, 3)) # (width, height, color channel (R, G, B))
print(random_image_tensor.ndim) # 3 dimensional (matrix essentially) (number of nested arrays)
print(random_image_tensor.shape)

3
torch.Size([224, 224, 3])


In [40]:
# zeros tensor
zeros = torch.zeros(size=(3, 4))
print(zeros)
print(zeros.ndim) # 2 dimensional (matrix essentially) (number of nested arrays)
print(zeros.shape)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
2
torch.Size([3, 4])


In [39]:
r = torch.tensor([[1, 2, 3], [4, 5, 6]])
# z = torch.zeros_like(r)
k = torch.rand(2, 3)
r * k

tensor([[0.7616, 0.8478, 0.5302],
        [0.2763, 1.6523, 3.9702]])

In [42]:
# ones tensor
ones = torch.ones(size=(3, 4))
print(ones)
print(ones.ndim) # 2 dimensional (matrix essentially) (number of nested arrays)
print(ones.shape)
print(ones.dtype) # default type is float32

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
2
torch.Size([3, 4])
torch.float32


In [47]:
# Creating a range of tensors

range_tensor = torch.arange(start=0, end=10, step=2)
print(range_tensor)
print(range_tensor.dtype) # default type is int64

tensor([0, 2, 4, 6, 8])
torch.int64


In [48]:

range_tensor = torch.arange(start=0, end=10, step=2)
print(range_tensor)
print(range_tensor.dtype) # default type is int64

tensor([0, 2, 4, 6, 8])
torch.int64
