### Tensor operations
- Addition
- Subtraction
- Multiplication (element-wise)
- Division
- Matrix multiplication (dot product)

In [1]:
import torch
import matplotlib.pyplot as plt

In [13]:
# Addition
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
print(tensor1 + 10) # addition with a scalar
print(tensor1 + tensor2) # addition with another tensor
print(torch.add(tensor1 + 2, tensor2 + 3)) # matrix addition

tensor([11, 12, 13])
tensor([5, 7, 9])
tensor([10, 12, 14])


In [10]:
# Multiplication
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([[4, 5, 6], [2, 0, 1]])
print(tensor1 * 10) # multiplication with a scalar (element-wise)
print(tensor1 * tensor2) # multiplication with another tensor (element-wise)
print(torch.mul(tensor1 + 2, tensor2 + 3)) # matrix multiplication (element-wise)

tensor([10, 20, 30])
tensor([[ 4, 10, 18],
        [ 2,  0,  3]])
tensor([[21, 32, 45],
        [15, 12, 20]])


In [12]:
# Subtraction
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([[4, 5, 6], [2, 0, 1]])
print(tensor1 - 5) # subtraction with a scalar
print(tensor1 - tensor2) # subtraction with another tensor
print(torch.sub(tensor1 + 2, tensor2 + 3)) # matrix subtraction

tensor([-4, -3, -2])
tensor([[-3, -3, -3],
        [-1,  2,  2]])
tensor([[-4, -4, -4],
        [-2,  1,  1]])


In [15]:
# Division
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([[4, 5, 6], [2, 3, 1]])
print(tensor1 / 5) # division with a scalar
print(tensor1 / tensor2) # division with another tensor
print(torch.div(tensor1 + 2, tensor2 + 3)) # matrix division

tensor([0.2000, 0.4000, 0.6000])
tensor([[0.2500, 0.4000, 0.5000],
        [0.5000, 0.6667, 3.0000]])
tensor([[0.4286, 0.5000, 0.5556],
        [0.6000, 0.6667, 1.2500]])


In [16]:
# Matrix multiplication
tensor1 = torch.tensor([[1, 2], [3, 4]])
tensor2 = torch.tensor([[5, 6], [7, 8]])
print(torch.matmul(tensor1, tensor2)) # matrix multiplication (dot product)
print(torch.matmul(tensor1, tensor2).shape) # matrix multiplication (dot product)

tensor([[19, 22],
        [43, 50]])
torch.Size([2, 2])


In [29]:
# element-wise vs dot product
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
print(tensor1 * tensor2) # element-wise
print(torch.matmul(tensor1, tensor2)) # dot product
print(torch.dot(tensor1, tensor2)) # dot product (same as above)
print(tensor1 @ tensor2) # dot product (same as above)

tensor([ 4, 10, 18])
tensor(32)
tensor(32)
tensor(32)


RuntimeError: self must be a matrix

In [30]:
print(torch.rand(3, 4) @ torch.rand(4, 3)) # size of the result is (3 (row from tensor1), 3 (column from tensor2))
print(torch.rand(2, 3) @ torch.rand(3, 2)) # size of the result is 2
print(torch.mm(torch.rand(2, 3), torch.rand(3, 2))) # size of the result is 2 (mm is an alias for matmul)

tensor([[0.4016, 1.9845, 1.0880],
        [0.3481, 1.8310, 1.2406],
        [0.1918, 0.6081, 0.8947]])
tensor([[0.1746, 0.4190],
        [0.4933, 1.1967]])
tensor([[0.4450, 0.3740],
        [0.3106, 0.2030]])


In [32]:
# transpose
tensor1 = torch.tensor([[1, 2], [3, 4], [5, 6]])
print(tensor1)
print(tensor1.shape)
print(tensor1.t()) # transpose
print(tensor1.t().shape) # transpose

tensor([[1, 2],
        [3, 4],
        [5, 6]])
torch.Size([3, 2])
tensor([[1, 3, 5],
        [2, 4, 6]])
torch.Size([2, 3])


### Tensor Aggregations
- Min
- Max
- Mean
- Sum
- Standard Deviation

In [34]:
x = torch.arange(0, 100, 5, dtype=torch.float32) # default dtype is ong

# torch.min(), torch.max(), torch.mean(), torch.sum()
x.min(), x.max(), x.mean(), x.sum()

(tensor(0.), tensor(95.), tensor(47.5000), tensor(950.))

In [37]:
# Positional arguments (index position)
print(x.argmin(), x.argmax())
print(x[x.argmin()], x[x.argmax()])

tensor(0) tensor(19)
tensor(0.) tensor(95.)


In [36]:
# standard deviation
# standard deviation is the square root of the variance
# A standard deviation (or σ) is a measure of how dispersed the data is in relation to the mean. Low, 
# or small, standard deviation indicates data are clustered tightly around the mean, and high, or large, 
# standard deviation indicates data are more spread out.
x.std()

tensor(29.5804)

### Reshaping, stacking, squeezing and expanding tensors
- Reshaping: reshape a tensor to a defined shape
- View: Return a view of an input tensor of certain shape without altering the original tensor (same memory location)
- Stacking: combine multiple tensors on top of each other (vstack) or side by side (hstack)
- Squeezing: removes all "1" dimensions from a tensor
- Expanding (unsqueeze): add a "1" dimension to a tensor
- Permute: Returns a view of the input with its dimensions rearranged according to a specified order.

In [43]:
# reshape
x = torch.arange(1, 10) # 9 elements
print(x, x.shape)
x_reshape = x.reshape(3, 3) # when you multiply the shape, you get the same number of elements in "x"
print(x_reshape, x_reshape.shape)

x = torch.arange(0, 15)
x_reshape = x.reshape(3, 5)
print(x_reshape, x_reshape.shape)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]) torch.Size([9])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]) torch.Size([3, 3])
tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]) torch.Size([3, 5])


In [45]:
# Change the view
x = torch.arange(1, 10) 
# changing z changes x (because a view of a tensor shares the same memory as the original tensor)
z = x.view(3, 3)
print(z, z.shape)

z[:, 0] = 5 # z[row (":" means all rows), column] = value
z, x

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]) torch.Size([3, 3])


(tensor([[5, 2, 3],
         [5, 5, 6],
         [5, 8, 9]]),
 tensor([5, 2, 3, 5, 5, 6, 5, 8, 9]))

In [50]:
g = torch.rand(2, 2, 2)
print(g[:, :, 0]) # returns the first element in each row
print(g)

tensor([[0.6933, 0.8318],
        [0.1271, 0.0737]])
tensor([[[0.6933, 0.6722],
         [0.8318, 0.6525]],

        [[0.1271, 0.2536],
         [0.0737, 0.6608]]])
