In [1]:
import torch
import numpy as np

In [5]:
k = torch.rand(7, 7)
op = k @ torch.rand(1, 7).T
print(op, op.shape)

tensor([[2.9186],
        [2.0572],
        [2.1108],
        [2.7854],
        [2.3311],
        [1.8211],
        [1.7679]]) torch.Size([7, 1])


In [6]:
seed = 0
torch.manual_seed(seed)
k = torch.rand(7, 7)
op = k @ torch.rand(1, 7).T
print(op, op.shape)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]]) torch.Size([7, 1])


In [8]:
torch.cuda.manual_seed(1234)
k = torch.rand(7, 7, device="cuda")
op = k @ torch.rand(1, 7, device="cuda").T
print(op, op.shape)

tensor([[2.5893],
        [2.1242],
        [1.8872],
        [2.5468],
        [1.7516],
        [1.6445],
        [1.6517]], device='cuda:0') torch.Size([7, 1])


In [14]:
torch.manual_seed(1234)
k1 = torch.rand(2, 3)
k2 = torch.rand(2, 3)
device = "cuda" if torch.cuda.is_available() else "cpu"
k1.to(device)
k2.to(device)
op = k1 @ k2.T
print(op, op.shape)
print(op.max())
print(op.min())
print(op.argmax())
print(op.argmin())

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]]) torch.Size([2, 2])
tensor(0.5617)
tensor(0.3647)
tensor(3)
tensor(0)


In [13]:
torch.manual_seed(7)
k = torch.rand(1, 1, 1, 10)
l = k.squeeze()
sq = torch.rand_like(k).squeeze()
print(sq, sq.shape)
print(k, k.shape)

tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
tensor([[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
          0.3653, 0.8513]]]) torch.Size([1, 1, 10])
tensor([[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]]) torch.Size([1, 10])
